version: '3'
services:
#  mesh:
#    image: mdm:latest
#    ports:
#      - "4141:4141"
#      - "2222:2222"
#      - "9990:9990"
#      - "4140:4140"
#      - "8080:8080"
#    environment:
#      - "SR_APP_KEY=AP-FDS-MDM-FOUNDATION"
#      - "SR_APP_ENV=stage"
#      - "SR_PRODUCER_HOST=api.fds.wal-mart.com"
#      - "SPRING_PROFILES_ACTIVE=stage"
#      - "SR_APP_ADDR=http://localhost:8080"
  mesh:
    image: receive-mesh
    ports:
      - "4141:4141"
      - "2222:2222"
      - "9990:9990"
      - "4140:4140"
      - "8080:8080"
    environment:
      - "SR_APP_KEY=AP-FDS-RECEIVING"
      - "SR_APP_ENV=dev"
      - "SR_PRODUCER_HOST=api.fds.stg.wal-mart.com"
      - "STRATI_ENVIRONMENT_TYPE=local"
      - "SPRING_PROFILES_ACTIVE=dev-us"

#  api:
#    image: apfsregistrydev.azurecr.io/ap-fds-receive:2.1.107-SNAPSHOT
#    environment:
#      - "SPRING_PROFILES_ACTIVE=prod-us"

#version: "3.3"
#services:
#  mesh:
#    image: fdsregistryrelease.azurecr.io/servicemesh:0.1.9
#    ports:
#      - "8080:4141"
#    environment:
#      - "SR_APP_KEY=AP-FDS-INVOICE-FINANCIAL-TRANSACTION"
#      - "SR_APP_ENV=prod-us"
#      - "SR_APP_ADDR=http://api:8080"
#      - "STRATI_ENVIRONMENT_TYPE=prod"

#  api:
#    image: fdsregistryrelease.azurecr.io/invoice-financial-transaction:1.1.91
#    environment:
#      - "SPRING_PROFILES_ACTIVE=prod"